### ISSUE TITLE
Neos 4.1 Error message 

### ISSUE THREAD

**Issue by MKdent** [psmb/Psmb.Newsletter#13]
Hello, 
I get the following Error message after installing newsletter with composer and latest commit e085f18.
Any missing adjustment of namespace? Maybe you can help...Thank you!
Required class "TYPO3\Eel\ProtectedContextAwareInterface" could not be loaded properly for reflection.
Possible reasons are:

* Requiring non-existent classes
* Using non-supported annotations
* Class-/filename missmatch.

**Comment by mgoldbeck** [comment]
Hi sorry for this.
Right now there is the merge for one of the two Pull Requests missing for https://github.com/psmb/Psmb.Registry being compatible with Flow5.

After that 
`composer require psmb/registry` 
should definitely fetch the newest version.

If this is urgent for you you can also use one fork in the meantime.
For example https://github.com/mindscreen/Psmb.Registry ;)

**Comment by MKdent** [comment]
Great! Thank you!
