### ISSUE TITLE
Error : The URI must be a valid string

### ISSUE THREAD

**Issue by MKdent** [psmb/Psmb.Newsletter#15]
Hello,
after successfully requesting psmb.newsletter, I run into this problem: When I send my name and email address for subscription I get this error below. 
Is it due to misconfiguration of the plugin or wrong format of url?
Hope this is the right place in GitHub issues to ask about such problems. I've never been active here.

Exception #1176550571 in line 89 Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Psmb_Newsletter_Service_FusionMailService.php: The URI must be a valid string.

HTTP REQUEST:
POST /~newsletter/register HTTP/1.1
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 1022
Upgrade-Insecure-Requests: 1
Dnt: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8

--newsletter%5B__referrer%5D%5B%40package%5D=Psmb.Newsletter&--newsletter%5B__referrer%5D%5B%40subpackage%5D=&--newsletter%5B__referrer%5D%5B%40controller%5D=Subscription&--newsletter%5B__referrer%5D%5B%40action%5D=index&--newsletter%5B__referrer%5D%5Barguments%5D=YTowOnt93536b25b46d0999aa0b95351872e78ecd166e395&__referrer%5B%40package%5D=Neos.Neos&__referrer%5B%40subpackage%5D=&__referrer%5B%40controller%5D=Frontend%5CNode&__referrer%5B%40action%5D=show&__referrer%5Barguments%5D=YToxOntzOjQ6Im5vZGUiO3M6MzU6Ii9zaXRlcy9uZW9zZGVtb0BsaXZlO2xhbmd1YWdlPWVuX1VTIjt966d5716b2eb572aa5d2154286c8a1f4664a4f4cc&--newsletter%5Bsubscriber%5D%5Bsubscriptions%5D=&--newsletter%5B__trustedProperties%5D=a%3A1%3A%7Bs%3A10%3A%22subscriber%22%3Ba%3A3%3A%7Bs%3A4%3A%22name%22%3Bi%3A1%3Bs%3A5%3A%22email%22%3Bi%3A1%3Bs%3A13%3A%22subscriptions%22%3Ba%3A1%3A%7Bi%3A0%3Bi%3A1%3B%7D%7D%7D5f251935853220af8e38fefb130547ec4746e7c1&--newsletter%5Bsubscriber%5D%5Bname%5D=mich&--newsletter%5Bsubscriber%5D%5Bemail%5D=mk%40gmail.com

HTTP RESPONSE:
[response was empty]

**Comment by mgoldbeck** [comment]
Hi,

did you configure 
`Neos.Flow.http.baseUri: 'http://yourdomain.tld/'`

in your Settings?

**Comment by MKdent** [comment]
Hi, that solved it.Perfect!

**Comment by MKdent** [comment]
Hi, that solved it. Great!
